myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from newsletter import views as newsletter_views


# from newsletter import views as newsletter_views
# from videos import urls as videos_url



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',newsletter_views.home, name = "home"),
	# url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls'),),
    url(r'^videos/', include('videos.urls')),
    url(r'^categories/', include('videos.urls_categories'),name = "categories"),
]

videos/urls.py
from django.conf.urls import include, url
# from videos.views import video_detail_view_func

from .views import VideoDetailView, VideoListView


# from newsletter import views as newsletter_views
# from videos import urls as videos_url



urlpatterns = [

    url(r'^$',VideoListView.as_view(), name = "video_list"),
    url(r'^(?P<pk>\d+)', VideoDetailView.as_view(), name = "video_detail"),
]

newsletter/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class SignUp(models.Model):
	email = models.EmailField()
	full_name = models.CharField(max_length = 120, blank=False, null = True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now = False)
	updated = models.DateTimeField(auto_now_add=False, auto_now = True)

	def __unicode__(self):
		return str(self.email)

videos/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models


# Create your models here.
class VideoQuerySet(models.query.QuerySet):
	def active(self):
		return self.filter(active=True)

class VideoManager(models.Manager):
	def get_queryset(self):
		return VideoQuerySet(self.model, using = self._db)

	def all(self, *args, **kwargs):
		return self.get_queryset().active()

	def get_related(self, instance):
		products_one = self.get_queryset().filter(categories__in=instance.categories.all())
		# products_two = self.get_queryset().filter(default = instance.default)
		qs = products_one.exclude(pk=instance.pk).distinct()
		return qs




class Video(models.Model):
	title = models.CharField(max_length=240)
	description = models.TextField(blank = True,null=True)
	video_url = models.CharField(max_length=240)
	video_img_url = models.CharField(max_length=240)
	active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True,auto_now=False)
	categories = models.ManyToManyField('Category')
	default = models.ForeignKey('Category', related_name='default_category',null = True, blank = True)	


	objects = VideoManager()

	class Meta:
		ordering = ["title"]

	def __unicode__(self):
		return str(self.title)

	def get_absolute_url(self):
		return reverse("video_detail", kwargs={"pk":self.pk})


class Category(models.Model):
	title = models.CharField(max_length=120, unique = True)
	slug = models.SlugField(unique=True)
	category_img_url = models.TextField(null=True, blank=True)
	description = models.TextField(null=True, blank=True)
	active = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True, auto_now=False)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("category_detail", kwargs={"slug":self.slug})

	def get_video_list(self):
		return Video.objects.all.filter()

newsletter/forms.py
from django import forms

from .models import SignUp


class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name','email']


	# def clean_email(self):
	# 	email = self.cleaned_data.get('email')
	# 	email_base, provider = email.split("@")
	# 	domain, extension = provider.split('.')
	# 	if not domain == 'USC':
	# 		raise forms.ValidationError("Please make sure you use your USC email.")
	# 	if not extension == "edu":
	# 		raise forms.ValidationError("Please use a valid .EDU email address")
	# 	return email

	# def clean_full_name(self):
	# 	full_name = self.cleaned_data.get('full_name')
	# 	#write validation code.
	# 	return full_name

videos/forms.py
from django import forms

from .models import Video, Category
from django.utils.text import slugify

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = ['title','slug','category_img_url','active']



class VideoForm(forms.ModelForm):
	class Meta:
		model = Video
		fields = ['title','categories','video_url','video_img_url','active']
		# fields = ['title','description','video_url']


	# def clean_email(self):
	# 	email = self.cleaned_data.get('email')
	# 	email_base, provider = email.split("@")
	# 	domain, extension = provider.split('.')
	# 	if not domain == 'USC':
	# 		raise forms.ValidationError("Please make sure you use your USC email.")
	# 	if not extension == "edu":
	# 		raise forms.ValidationError("Please use a valid .EDU email address")
	# 	return email

	# def clean_full_name(self):
	# 	full_name = self.cleaned_data.get('full_name')
	# 	#write validation code.
	# 	return full_name

newsletter/views.py
from django.shortcuts import render
from .forms import SignUpForm
import random
from videos.models import Video



# Create your views here.

def home(request):
	# if request.method == "POST":
	# 	# print request.POST
	title = "Welcome to my site"
	form = SignUpForm(request.POST or None)

	random_idx = random.randint(0, Video.objects.count() - 1)
	random_video = Video.objects.all()[random_idx]
	random_videos = Video.objects.all().order_by('?')[:8]
	context = {
		"title":title,
		"form":form,
		"random_video":random_video,
		"random_videos":random_videos,
	}
	return render(request,"home.html",context)

videos/views.py
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
import random
# Create your views here.

from .models import Video, Category

class VideoDetailView(DetailView):
	model = Video
	def get_context_data(self,*args,**kwargs):
		context = super(VideoDetailView, self).get_context_data(*args, **kwargs)
		instance = self.get_object()
		context["related"] = sorted(Video.objects.get_related(instance), key=lambda x:random.random())
		return context


class VideoListView(ListView):
	model = Video
	def get_context_data(self, **kwargs):
		context = super(VideoListView, self).get_context_data(**kwargs)
		context['number'] = 1
		return context
	def get_queryset(self,*args,**kwargs):
		qs = super(VideoListView,self).get_queryset(*args,**kwargs)
		query = self.request.GET.get("q")
		if query:
			qs = self.model.objects.filter(
				Q(title__icontains=query) |
				Q(description__icontains=query)
				)
		return qs




class CategoryListView(ListView):
	model = Category
	queryset = Category.objects.all()

class CategoryDetailView(DetailView):
	model = Category





# def video_detail_view_func(request, id):
# 	video_instance = Video.objects.get(id=id)
# 	template = "videos/video_detail.html"
# 	context = {
# 		"object": video_instance
# 	}
# 	return render(request, template, context)

myproject/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}Xiaochen's Music Site{% endblock %}</title>

    {% include 'head_css.html' %}

  </head>

  <body>
  {% include 'navbar.html' %}

{% block jumbotron %}
<br><br>
<div class="jumbotron hidden-xs">


      <div class="container">
      {% block jumbotron_content %}
      {% endblock %}
      </div>

</div>
{% endblock %}

<div class = "container">
<br><br>
    {% block content %}
    {% endblock %}
</div>      
    {% include "javascript.html" %}   
  </body>
</html>

myproject/templates/head_css.html
{% load staticfiles %}
<!-- Bootstrap core CSS -->
<!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
<!-- Custom styles for this template -->
<!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'css/custom.css' %}" rel="stylesheet">

<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
<script src="../../assets/js/ie-emulation-modes-warning.js"></script>
-->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

myproject/templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }}{% endblock %}

{% block jumbotron_content %}
<div class = "row">
	<div class = "col-sm-6 col-md-7">
		<br><br>
		<iframe width="560" height="315" src="https://www.youtube.com/embed/UmU4KX7nxYs" frameborder="0" allowfullscreen></iframe>
	</div>

	<div class = "col-sm-6 col-md-5 white-letter ">
	<br><br>
		<h1 class = "lead">Enjoy</h1>
		<p></p>
		<br>
		<p>The Best of Classical Music - Mozart, Beethoven, Bach, Chopin... </p>
		<p>
		<br>
		<a class="btn btn-lg red-background white-letter" href="{{random_video.get_absolute_url}}" role="button">
		<span>Pick one</span> </a>
		</p>
	</div>
</div>
{% endblock %}



{% block content %}
<div class = 'row'>
	{% for video in random_videos %}
		<div class = "col-sm-6 col-md-3" style = "">
			<a href="{{ video.get_absolute_url }}">
				<img style="width:100%" src='{{video.video_img_url}}'/>
				<br>
				<div class="title">
					{{video.title}}
				</div>
				<br>
			</a>
		</div>

	{% cycle '' '' '' '</div><div class = "row">' %}
	{% endfor %}
</div>

{% endblock %}
</div>

myproject/templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

myproject/templates/navbar.html
   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class = "conatiner-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><span class="white-letter">Home</span></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class= "headerDivider white-letter"><a href="/categories"><span class = "white-letter">Categories</span></a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">

          {% if request.user.is_authenticated %}
            <li><a href="{% url 'auth_logout' %}"><i class="fa fa-sign-out fa-lg" aria-hidden="true"></i><span class = "white-letter"> Sign Out ({{user}})&nbsp&nbsp&nbsp&nbsp&nbsp</span> </i></a> </li>
            <li>&nbsp&nbsp&nbsp</li>
            {% else %}

              {%if not "/accounts/register" in request.get_full_path %}
              <li><a href="{% url 'registration_register' %}"><i class="fa fa-user-plus " aria-hidden="true"></i><span class= "white-letter"> Register&nbsp&nbsp&nbsp&nbsp&nbsp</span></a></li>
              {% endif %}

              {%if not "/accounts/login" in request.get_full_path %}

                <li><a href="{% url 'auth_login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i><span class= "white-letter">Sign in&nbsp&nbsp&nbsp&nbsp&nbsp</span></a></li>
<!--                 <form class='navbar-form navbar-right' method='POST' action='{% url "auth_login" %}'>{% csrf_token %}
                  <div class='form-group'>
                      <input type='text' class='form-control' name='username' placeholder='Username' /> 
                  </div>
                  <div class='form-group'>
                      <input type='password' class='form-control' name='password' placeholder='Password' />
                  </div>
                  <button type='submit' class='btn btn-default'><span class= "hover-underline"> Sign in </span></button>
                </form> -->
                <li>&nbsp&nbsp&nbsp</li>
              {% endif %}

            {% endif %}
          </ul>
                    <form class="navbar-form navbar-right" method = "GET" role="search" action = '{% url "video_list" %}'>
            <div class="form-group">
              <input type="text" size="30" class="form-control" placeholder="Search" name = "q">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>


        </div><!--/.nav-collapse -->
      </div>
    </nav>

myproject/templates/videos/category_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }}{% endblock %}


{% block jumbotron %}
<!-- <div class = "row">

<div class = "col-md-7">
	<iframe width="560" height="315" src="https://www.youtube.com/embed/UmU4KX7nxYs" frameborder="0" allowfullscreen></iframe>
</div>

<div class = "col-md-5">
	<h1 class = "lead">Enjoy</h1>
	<p></p>
	<br>
	<p>The Best of Classical Music - Mozart, Beethoven, Bach, Chopin... </p>
	<p>
	<br>
	<a class="btn btn-lg btn-success" href="" role="button">
	<span class = "hover-black">Pick one</span> </a>
	</p>
</div>



</div> -->

{% endblock %}




{% block content %}
<!-- <div class = "row">
<div class = "col-md-3 pull-right">
<h1 class = "lead">{{ title }}</h1>
<form method='POST' action=''>{% csrf_token %}
{{ form | crispy }}

<input type='submit' value='Sign Up' />
</form>
</div>
</div> -->
<div class = "container"
<br><br>
<h3 class = "lead">{{object.title}}</h3>
<hr>
<div class = 'row'>
	{% for video in object.video_set.all %}
	<div class = "col-sm-6 col-md-3" style = "">
		<a href="{{ video.get_absolute_url }}">
				<img style="width:100%" src='{{video.video_img_url}}'/>
			<br>
			<div class = "title">
				{{video.title}}
			</div>
			<br>
		</a>
	</div>

	{% cycle '' '' '' '</div><div class = "row">' %}
	{% endfor %}
</div>
{% endblock %}

myproject/templates/videos/category_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }}{% endblock %}


{% block jumbotron %}
{% endblock %}


<br>

{% block content %}
<br><br>
<div class = 'row'>
	{% for category in category_list %}
	<div class = "col-sm-6 col-md-3" style = "">
		<a href="{{ category.get_absolute_url }}">
				<img style="width:100%" src='{{category.category_img_url}}'/>
			<div class = "lead" style ="text-align: center">
				{{category.title}}
			</div>
			<br>
		</a>
	</div>

	{% cycle '' '' '' '</div><div class = "row">' %}
	{% endfor %}


</div>

{% endblock %}

myproject/templates/videos/video_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }}{% endblock %}


{% block jumbotron%}
{% endblock %}




{% block content %}
<br><br><br>
<div class = 'row'>
	<div class = "col-md-8">
		<div class = 'row'>
			<h2 class = "lead text-center">{{object.title}}</h2>
		</div>
		<br>
		<div class = 'row'>
			<div class = "video-container">
			{{object.video_url | safe}}
			</div>
		</div>
		<br>
	</div>
	<div class = "col-md-2 col-md-offset-2">
		<div class = 'row'>
			<h3>Related Videos</h3>
		</div>
		<hr>
		{% for video in related %}
		<div class = 'row'>

			<a href="{{ video.get_absolute_url }}">
				<img style="width:100%" src='{{video.video_img_url}}'/>
				<div>
					<p class = "text-center">{{video.title}}<p>
				</div>
			</a>
		</div>
		<br>
		{% endfor %}
	</div>
</div>
{% endblock %}

myproject/templates/videos/video_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Welcome | {{ block.super }}{% endblock %}


{% block jumbotron%}
{% endblock %}



{% block content %}
<br><br>
<div class = 'row'>
	{% for video in video_list %}
		<div class = "col-sm-6 col-md-3" style = "">
			<a href="{{ video.get_absolute_url }}">
				<img style="width:100%" src='{{video.video_img_url}}'/>
				<br>
				<div class ="title">{{video.title}}</div>
				<br>
			</a>
		</div>

	{% cycle '' '' '' '</div><div class = "row">' %}
	{% endfor %}
</div>
{% endblock %}